# Generated by Django 4.2.2 on 2023-06-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_name", models.CharField(max_length=200)),
                (
                    "plant_status",
                    models.IntegerField(
                        choices=[
                            (1, "Brilliant"),
                            (2, "Good"),
                            (3, "OK"),
                            (4, "Bad"),
                            (5, "Dead"),
                            (6, "Missing"),
                        ],
                        default=3,
                    ),
                ),
                ("soil_moisture", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reportPlantStatus.plant",
                    ),
                ),
            ],
            options={"ordering": ["created_on"],},
        ),
    ]
