# Generated by Django 4.2.8 on 2023-12-26 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportPlantStatus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservoir_name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="image/")),
                ("details", models.TextField(blank=True, null=True)),
                ("water_level", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="comment", old_name="body", new_name="contents",
        ),
        migrations.RenameField(
            model_name="comment", old_name="name", new_name="title",
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
        migrations.AddField(
            model_name="plant",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="user",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="plant",
            name="reservoir",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reportPlantStatus.reservoir",
            ),
        ),
    ]
