# Generated by Django 4.2.8 on 2023-12-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reportPlantStatus", "0002_reservoir_rename_body_comment_contents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reportPlantStatus.plant",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="reservoir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reportPlantStatus.reservoir",
            ),
        ),
    ]
