# Generated by Django 4.2.8 on 2023-12-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportPlantStatus", "0005_reservoir_reservoir_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservoir",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
