# Generated by Django 4.2.8 on 2023-12-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportPlantStatus", "0006_alter_reservoir_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
